name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v4.1.5
      - name: Build manifests
        run: make release-manifests
      - name: Release manifests
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v0.1.15
        with:
          files: |
            _output/components.yaml
            _output/high-availability.yaml
            _output/high-availability-1.21+.yaml
      - name: Build binaries
        run: make build-all
      - name: Release binaries
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v0.1.15
        with:
          files: |
            _output/metrics-server-*
